kind: Service
apiVersion: v1
metadata:
  name: nodejs-sample
  namespace: demo-gitops
  labels:
    app: nodejs-sample
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8081
  selector:
    app: nodejs-sample
    deploymentconfig: nodejs-sample
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
